apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app.kubernetes.io/name: cloudpulse
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: cloudpulse
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cloudpulse
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8000
      targetPort: http
