apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: cloudpulse
    app.kubernetes.io/component: postgres
    app.kubernetes.io/part-of: cloudpulse
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cloudpulse
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
