apiVersion: v1
kind: Secret
metadata:
  name: cloudpulse-secret
  labels:
    app.kubernetes.io/name: cloudpulse
    app.kubernetes.io/part-of: cloudpulse
type: Opaque
stringData:
  POSTGRES_PASSWORD: cloudpulse
